name: neo4dart
description: Dart package to query Neo4J database
version: 0.0.1
homepage: https://github.com/ClementG63/Neo4Dart

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  http: 0.13.5
  mockito: 5.2.0
  test: 1.21.4
dev_dependencies:
  flutter_lints: 2.0.1
