name: neo4driver
description: Dart driver to manipulate the Neo4J database with the Neo4J Rest API.
version: 1.0.3
homepage: https://github.com/ClementG63/Neo4Dart

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  http: ^0.13.5
dev_dependencies:
  flutter_lints: 2.0.1
  test: 1.21.4
  mockito: 5.2.0